dod-advana/gamechanger-data

- common/document_parser/process.py
fixes bug that was crashing doc parser runs
> fix filter to use mime check and include pdfs

- README.md
Just trying out pull requests.
> Trying things out

- configuration/.gitignore
... to accomodate eda_local.json and other such files in future
> Makes .gitignore for configuration/app-config more flexible

- dataPipelines/gc_neo4j_publisher/cli.py
- dataPipelines/gc_neo4j_publisher/neo4j_publisher.py
- dataPipelines/gc_neo4j_publisher/utils.py
This updates the neo4j publisher to use the new neo4j plugin when ingesting the data. Greatly speeds up ingest times and fixes errors there were being seen.
> Lyons neo4j publisher v2

- common/document_parser/ref_utils.py
- common/document_parser/test_ref.py
EO and Army fixes for matching to doc_types
> fixing references eo and army to doc_type

- configuration/elasticsearch-config/dev-entities.json
- configuration/elasticsearch-config/local-entities.json
- configuration/elasticsearch-config/prod-entities.json
fixing mappings for entities in prod. related to issue of searches not working for topics and orgs
> fixing mappings

- configuration/elasticsearch-config/dev.json
- configuration/elasticsearch-config/local.json
- configuration/elasticsearch-config/prod.json
Updated mappings for dev + prod
> Updated display mappings for es to include gc_english + standard and other keywords

- common/document_parser/parsers/eda_contract_search/post_process.py
- common/document_parser/parsers/policy_analytics/display_mappings.py
- common/document_parser/parsers/policy_analytics/post_process.py
update post process and to use meta data for display properties when available, add warning to stop adding in to display mappings file
> display-mappings-in-crawlers

- dataPipelines/gc_ingest/pipelines/core/configs.py
- dataPipelines/gc_ingest/pipelines/core/steps.py
- dataPipelines/gc_thumbnails/cli.py
- dataPipelines/gc_thumbnails/utils.py
Multiprocessing capability for thumbnail generation. Produces close to a 10x speedup.
> Multiprocessing thumbnails

- dataPipelines/gc_ingest/pipelines/clone/configs.py
- dataPipelines/gc_manual_metadata/gc_manual_metadata.py
- paasJobs/jobs/configs/s3_upload_NGA.conf.sh
- paasJobs/jobs/s3_upload.sh
this config uses S3_RAW_INGEST_PREFIX="advana-raw-zone/gamechanger-test/pdf" to test run
which has 103 files in it
> allow env var for bucket prefix, clone or core, and create NGA config

- dataPipelines/gc_crawler_status_tracker/gc_crawler_status_tracker.py
Skips the revocation step for the crawler legislation_pubs.
> Skip revocations for legislation

- dataPipelines/gc_crawler_status_tracker/gc_crawler_status_tracker.py
> recommitting the legislation revoker fix

- paasJobs/jobs/configs/create_clone.conf.sh
- paasJobs/jobs/create_clone.sh
Turns notifications on for clone creation always, and makes the default for monitoring off
> change notifications on monitoring config

- dataPipelines/gc_ingest/pipelines/clone/configs.py
- dataPipelines/gc_ingest/pipelines/clone/steps.py
- dataPipelines/gc_ingest/pipelines/core/configs.py
- gc_clone_maker/gc_clone_maker.py
> adding s3 thread parameter to clone config

- common/document_parser/lib/summary.py
Summaries aren't currently used, so for now we're commenting out the expensive gensim in parsing until it's revisited in the future
> return blank string for summary

- common/document_parser/lib/entities.py
- common/document_parser/lib/topics.py
Changing topics data type and creating top entities
- test index at gamechanger_test4
-has equivalent PR for feature/UOT-123851 on web for changes that depends on this one.
> Changing topics data type and creating top entities

- rpa/rpa_landing_zone_mover.py
same as the dev merge. merging into main as a hotfix
> changes made for ingesting CAC data with utf-8 metadata

- rpa/rpa_landing_zone_mover.py
Another hotfix for the json decode error
> Extra correction to account for the ZipFiles

- dataPipelines/gc_db_utils/web/schemas.py
- gc_clone_maker/gc_clone_maker.py
Needs to be merged in concert with [web-PR](https://github.com/dod-advana/gamechanger-web/pull/322)
> remove unused fields

- common/utils/file_utils.py
- dataPipelines/gc_eda_pipeline/doc_extractor/doc_extractor.py
- dataPipelines/gc_ocr/utils.py
Jira ticket: https://jira.di2e.net/browse/UOT-132400
Description: PR to add in additional logic for "problematic pdfs"
Updates include:
> [UOT-132400] Update EDA OCR criteria/logic to include problematic pdfs

- configuration/elasticsearch-config/eda_dev.json
- configuration/elasticsearch-config/eda_local.json
Description: Adds in `p_raw_text` to ES mappings and adds in Similarity on the `p_raw_text` field
> [UOT-141639] Updates to ES index json files to incorporate similarity on p_raw_text

- common/document_parser/lib/summary.py
Removes gensinsumm import which causes parsing to fail as it has been commented out of gamechanger-ml
> Commenting out gensimsumm import

- common/document_parser/parsers/policy_analytics/parse.py
Updating the default display_doc_type value from doc_type to "Uncategorized"
> set defaults from doc_type -> Uncategorized

- configuration/elasticsearch-config/dev.json
- configuration/elasticsearch-config/prod.json
- dataPipelines/gc_neo4j_publisher/utils.py
neo4j's write function is out of date. Updating from alpha -> beta fixes this problem.
> updating neo4j write from alpha -> beta

- configuration/elasticsearch-config/local.json
- configuration/elasticsearch-config/prod.json
> changed es mappings for prod/local

- common/document_parser/parsers/policy_analytics/parse.py
- configuration/elasticsearch-config/dev.json
fixing bug shown by this image
> [Hotfix] Fixed Update Ingest Time Feature

- common/document_parser/parsers/policy_analytics/parse.py
> Fix html->pdf parse/ingesting

- common/document_parser/parsers/policy_analytics/parse.py
> html-pdf parse hotfix

- common/document_parser/lib/html_utils.py
Reverts dod-advana/gamechanger-data#279
> Revert "added SAMM nav bar removal; refactor overall remove_nav_bar func"

- paasJobs/neo4jTester.py
must have app configured
must be connected to big-ip edge vpn
must replace [vars] with correct credentials from app-config json()
> added neo4j connection test
