paasJobs/docker/crawl_and_download/run_job.sh

Recently found out changes in doc_name will create new entry and a duplicate doc so the Scrapy conversions need to be checked for this before being used

revert to non scrapy crawlers to avoid duplicate docs 

---

.gitattributes

Changes github language stats to more accurately reflect what we got in the repo. May not take effect until merged into main branch
Before:
After:

Adds git attrs to make github language stats more relevant

---

common/document_parser/lib/topics.py

Establish a requirement that a document must have more than 1 page to get topics.  If the document is only 1 page, the `topics_rs` field will be populated with an empty dict, otherwise it will be populated with up to 5 topics.
**For this change to take effect the jsons will need to be reprocessed**

Set Doc length requirements for Topics

---

dataPipelines/gc_neo4j_publisher/neo4j_publisher.py
dataPipelines/gc_neo4j_publisher/utils.py

Set the max_thread parameter in process_dir for neo4j updates to not have it hardcoded.

max_thread neo4j parameter

---

rpa/rpa_landing_zone_mover.py

CAC data breaks because of JSON decode errors. This PR rewrites the metdata files to exclude the beginning '\ufeff' at the beginning of the strings 
Note that it's easily possible to read JSONs with this utf error by setting encoding='utf-8-sig' in the open command, but we decided that rewriting the metadata files as a better strategy so different json types aren't mixed together in the databases.
We need to be careful after approval that we have write permissions wherever this code is executed.

changes made for ingesting CAC data with utf-8 metadata

---

dev_tools/requirements/gc-venv-current.txt
dev_tools/requirements/rhel8.locked.requirements.txt

The 'pdfdoc' codec in the version of the `pikepdf` library we use doesn't raise encoding errors in the expected way (raising `UnicodeEncodeError`) which breaks other code used in our HTML to PDF conversion. Bumping the version to 2.16.1 fixes the issue and allows the conversion to proceed.
see: https://github.com/pikepdf/pikepdf/issues/218

bugfix/UOT-129178 fix issue with pdfdoc text codec preventing HTML > PDF conversion

---

common/document_parser/lib/keywords.py
common/document_parser/lib/ml_features.py
common/document_parser/lib/organizations.py
common/document_parser/lib/page_rank.py
common/document_parser/lib/text_length.py
common/document_parser/parsers/policy_analytics/parse.py

Changes:
- changed filepaths to new data organization in gamechanger-ml
- removed unused rank feature functions
Testing:
- After re-installing gamechanger-ml, running pdf parser on directory of test pdfs worked:
```
python -m common.document_parser pdf-to-json -s "test_pdfs" -d "test_jsons"
python -m dataPipelines.gc_elasticsearch_publisher run -i "gamechanger_20211209_test" -d "test_jsons"
```
- Indexing JSONs in ES does not seem to mess up search (test index = `gamechanger_20211209_test`)

Task/uot 122338 - cleaning up rank features

---

common/document_parser/parsers/eda_contract_search/post_process.py
common/document_parser/parsers/policy_analytics/post_process.py
dataPipelines/gc_crawler_status_tracker/gc_crawler_status_tracker.py
dataPipelines/gc_db_utils/orch/models.py

This PR adds logic that allows documents to be ingested as revoked if the crawler marks the doc item as `is_revoked`. If this field is marked true by the crawler then it overrides the default behavior that always marks a document as _not_ revoked if it appears in the list of documents to ingest.
Depends on https://github.com/dod-advana/gamechanger-crawlers/pull/76

task/uot-127438 add logic to handle is_revoked field from scraped items

---

common/document_parser/lib/html_utils.py
common/document_parser/parsers/policy_analytics/parse.py

Ingest failed for the SAMM and TFM data sources because the xhtml2pdf library threw errors while trying to convert some of the HTML to PDF (in some cases the HTML was technically malformed, in other cases xhtml2pdf simply didn't properly support the html construct). 
This PR adds a "cleaning" step that fixes known problematic HTML before passing it to xhtml2pdf. This includes:
- removing empty table rows
- removing unparseable style attributes
- removing some empty attributes
- capping overly large rowspan attributes
Default CSS was added that shrinks tables to fit on PDF pages (xhtml2pdf will error if a table cell is larger than a page).
Also, currently xhtml2pdf will attempt to hit the network or filesystem to load any links (e.g. images or stylesheets) which seems undesirable for our …

bugfix/uot-122605 SAMM and TFM HTML Parse Fix 

---

dataPipelines/gc_crawler_status_tracker/gc_crawler_status_tracker.py
dataPipelines/gc_neo4j_publisher/neo4j_publisher.py

Adds logic to also check crawler used when updating Elasticsearch and Neo4j.
Also removes a broken optimization and moves conditional json parse of improperly json encoded strings server side.

task/uot-127438 fix logic to handle is_revoked field

---

dataPipelines/gc_neo4j_publisher/config.py

These may be changing again with the updates to the Neo4j publisher, but the old filepaths to data in the gamechangerml repo have since changed, updating them here.

bugfix - fixing the paths for data files

---

dev_tools/composectl/cli.py

Comments out legacy command preventing us from building docker images for local testing

remove cmd-ensure-baseline-image

---

dev_tools/universal_test_harness/tools/es.py

During setup, elasticsearch tries to remove an alias it shouldn't. this checks for that alias

remove the alias ilm-history-3 which elasticsearch tries to purge

---

dataPipelines/gc_neo4j_publisher/utils.py

Creates and writes three properties for nodes in Neo4j graph: Louvain community, Label Propagation community, and betweenness score. After writing the properties to nodes, tears down the temporary graph created to calculate the values.  [UOT-132229](https://jira.di2e.net/secure/RapidBoard.jspa?rapidView=19041&view=detail&selectedIssue=UOT-132229)
To test locally against a test directory of a subset of the corpus (TEST_CORPUS_DIR):
1. Start a local Neo4j DB locally (needs to have the Gamechanger plugins, gds and apoc plugins).
2. Run these commands:
```python -m configuration init local```
```python -m dataPipelines.gc_neo4j_publisher run -s TEST_CORPUS_DIR```
```(gc36) katherinedowdy@FVFYM0L5HV2G gamechanger-data % python -m dataPipelines.gc_neo4j_publisher run -s corpus_sample
Could not …
```

Task/uot 132229 - adding Neo4j cluster algos to graph

---

dataPipelines/gc_crawler_status_tracker/gc_crawler_status_tracker.py

Update from single doc revocation to batch revocation (batched by crawler) for ES.
This runs in 1/3 of the time as the single doc format we had before.

Update revocations es batch processing

---

setup.py

repo wasn't enforcing python3.8. this changes the setup script so that it does

commit change to enforce python3.8

---

dev_tools/requirements/gc-venv-current.txt

These reqs produce errors in the local install for the macOS. Removing to stop the errors.

removing faiss-gpu/cpu from reqs

---

common/document_parser/lib/ref_list.py
common/document_parser/ref_utils.py
common/document_parser/test_ref.py

This PR is part of the effort to enhance parser efficiency and specifically focuses on reference extraction.
[ref_utils.py](https://github.com/dod-advana/gamechanger-data/blob/dev/common/document_parser/ref_utils.py) creates a dictionary of reference types and regex patterns. 
_Originally_, each value in the dictionary was a tuple of patterns, where the first pattern was identical to the ending part of the second pattern. 
Ex:
```
(
re.compile(r"(([A-Z]+-)?[0-9]{4}\.\s*[0-9]{1,3}\s*(-[A-Z]+)?([E])?)", re.IGNORECASE),
re.compile(r"\b(((dod\s*placeholder)|(dod))\s*\)?\s*([A-Z]+-)?[0-9]{4}\.\s*[0-9]{1,3}\s*(-[A-Z]+)?([E])?)", re.IGNORECASE)
)
```
In [`look_for_general()`](https://github.com/dod-advana/gamechanger-data/blob/dev/common/document_parser/lib/ref_list.py), the second pattern (full …

Improve parser efficiency: reference extraction

---

common/document_parser/lib/ref_list.py

There are only 50 CFR Titles and 53 USC Titles.

fix ref extraction for USC and CFR Titles

---

common/document_parser/lib/ref_list.py

Don't allow Title 0 or CFR Title 0 to be a reference

fix ref extraction for title docs

---

common/document_parser/lib/document/field_names.py

- `page_num` -> `page_num_i` since the frontend is querying `page_num_i` specifically
- adding `orgs_rs`, `text_length_r`, and `kw_doc_score_r`. these were removed previously, adding them back in until frontend can make changes to remove them from their queries

page_num -> page_num_i

---

common/document_parser/lib/entities_utils.py

This code update modifies the logic used to created the `ENTITIES_LOOKUP_DICT` (used for mapping entities to a normalized name) such that for aliases the mapping is the actual `Name` (non-alias) for the entity. 
To test:
* Pull down this branch and pip install the gamechanger-data package in your env
* Option A: Create a test python scrip including the following:
```
from common.document_parser.lib import entities
print(entities.ENTITIES_LOOKUP_DICT.get(entities.replace_nonalpha_chars("GCCS-J")))
```
* Option B: Run pdf-to-json pipeline and verify that entities are being extracted with their standardized name e.g., if `DOD` is in the document, this should expand to `United States Department of Defense`

Standardize Entities During Extraction

---

dataPipelines/scripts/manifest_delete.py

Made changes to the delete_manifest.py script
1. Optimized code with set comprehension to increase speed and remove any duplicate records found in the cumulative_manifest and crawler_output  json files
2. Additional comments for readability and understanding.
3. Included the date in the filename for the updated manifest

Optimized code for delete_manifest.py script

---

configuration/elasticsearch-config/dev.json
configuration/elasticsearch-config/local.json
configuration/elasticsearch-config/prod.json

ES schema did not support configure_repo.sh.
Specifically,
`configuration/validators.py` was failing due to
`configuration/elasticsearch-config/dev.json`
having 'settings' before 'index'

hotfix ES config schema to support app config script

---

common/document_parser/lib/summary.py

In support of the summarization feature we need to add placeholder summaries that differ based on the deployment env. This PR should set the summary field in ES to "" if the env is PROD and "lorem ipsum...." otherwise. In addition to this PR we will be running a job on both dev and prod ES indexes to update the existing docs the same way.

Add Placeholder Summaries
